from metranova.ch_writer import BaseClickHouseOutput


class FlowEdgeOutput(BaseClickHouseOutput):

    def __init__(self):
        super().__init__()
        self.create_table_cmd = f"""
        CREATE TABLE IF NOT EXISTS {self.table} (
            `start_ts` DateTime64(3, 'UTC'),
            `end_ts` DateTime64(3, 'UTC'),
            `insert_ts` DateTime64(3, 'UTC') DEFAULT now(),
            `policy_originator` LowCardinality(Nullable(String)),
            `policy_level` LowCardinality(Nullable(String)),
            `policy_scopes` Array(LowCardinality(String)),
            `app_name` LowCardinality(Nullable(String)),
            `app_port` Nullable(UInt16),
            `bgp_as_path` Array(Nullable(UInt32)),
            `bgp_as_path_name` Array(Nullable(String)),
            `bgp_as_path_org` Array(Nullable(String)),
            `bgp_as_path_padding` Array(Nullable(UInt32)),
            `bgp_as_path_padded_len` Nullable(UInt32),
            `bgp_comms` Array(LowCardinality(Nullable(String))),
            `bgp_ecomms` Array(LowCardinality(Nullable(String))),
            `bgp_lcomms` Array(LowCardinality(Nullable(String))),
            `bgp_local_pref` Nullable(UInt32),
            `bgp_med` Nullable(UInt32),
            `bgp_next_hop` Nullable(IPv6),
            `bgp_peer_as_dst` Nullable(UInt32),
            `bgp_peer_as_dst_name` LowCardinality(Nullable(String)),
            `bgp_peer_as_dst_org` LowCardinality(Nullable(String)),
            `collector_id` LowCardinality(Nullable(String)),
            `country_scope` LowCardinality(Nullable(String)),
            `device_ip` Nullable(IPv6),
            `device_name` LowCardinality(Nullable(String)),
            `device_loc_name` LowCardinality(Nullable(String)),
            `device_loc_type` LowCardinality(Nullable(String)),
            `device_loc_lat` Nullable(Decimal(8, 6)),
            `device_loc_lon` Nullable(Decimal(9, 6)),
            `device_manufac` LowCardinality(Nullable(String)),
            `device_model` LowCardinality(Nullable(String)),
            `device_network` LowCardinality(Nullable(String)),
            `device_os` LowCardinality(Nullable(String)),
            `device_role` LowCardinality(Nullable(String)),
            `device_state` LowCardinality(Nullable(String)),
            `dscp` Nullable(UInt32),
            `dst_as_name` LowCardinality(Nullable(String)),
            `dst_asn` UInt32,
            `dst_continent` LowCardinality(Nullable(String)),
            `dst_country_name` LowCardinality(Nullable(String)),
            `dst_ip` IPv6,
            `dst_loc_lat` Nullable(Decimal(8, 6)),
            `dst_loc_lon` Nullable(Decimal(9, 6)),
            `dst_org` LowCardinality(Nullable(String)),
            `dst_port` UInt16,
            `dst_pref_loc_lat` Nullable(Decimal(8, 6)),
            `dst_pref_loc_lon` Nullable(Decimal(9, 6)),
            `dst_pref_org` LowCardinality(Nullable(String)),
            `dst_pub_asn` Nullable(UInt32),
            `dst_region_iso_code` LowCardinality(Nullable(String)),
            `dst_region_name` LowCardinality(Nullable(String)),
            `esdb_dst_org_full_name` LowCardinality(Nullable(String)),
            `esdb_dst_org_funding_agency` LowCardinality(Nullable(String)),
            `esdb_dst_org_hide` Bool,
            `esdb_dst_org_short_name` LowCardinality(Nullable(String)),
            `esdb_dst_org_types` Array(LowCardinality(Nullable(String))),
            `esdb_dst_svc_labels` Array(LowCardinality(Nullable(String))),
            `esdb_dst_svc_prefix_group_names` Array(LowCardinality(Nullable(String))),
            `esdb_dst_svc_types` Array(LowCardinality(Nullable(String))),
            `esdb_src_org_full_name` LowCardinality(Nullable(String)),
            `esdb_src_org_funding_agency` LowCardinality(Nullable(String)),
            `esdb_src_org_hide` Bool,
            `esdb_src_org_short_name` LowCardinality(Nullable(String)),
            `esdb_src_org_types` Array(LowCardinality(Nullable(String))),
            `esdb_src_svc_labels` Array(LowCardinality(Nullable(String))),
            `esdb_src_svc_prefix_group_names` Array(LowCardinality(Nullable(String))),
            `esdb_src_svc_types` Array(LowCardinality(Nullable(String))),
            `flow_type` LowCardinality(Nullable(String)),
            `ifin_description` Nullable(String),
            `ifin_device` Nullable(String),
            `ifin_id` Nullable(String),
            `ifin_ifindex` Nullable(UInt32),
            `ifin_edge` Bool,
            `ifin_ipv4` Nullable(IPv4),
            `ifin_ipv6` Nullable(IPv6),
            `ifin_name` Nullable(String),
            `ifin_netflow_index` Nullable(UInt32),
            `ifin_peer_as_name` LowCardinality(Nullable(String)),
            `ifin_peer_asn` Nullable(UInt32),
            `ifin_peer_ip` Nullable(IPv6),
            `ifin_port_name` Nullable(String),
            `ifin_remote_device` LowCardinality(Nullable(String)),
            `ifin_remote_full_name` LowCardinality(Nullable(String)),
            `ifin_remote_id` Nullable(String),
            `ifin_remote_lldp_device` LowCardinality(Nullable(String)),
            `ifin_remote_lldp_port` LowCardinality(Nullable(String)),
            `ifin_remote_loc_name` LowCardinality(Nullable(String)),
            `ifin_remote_loc_type` LowCardinality(Nullable(String)),
            `ifin_remote_loc_lat` Nullable(Decimal(8, 6)),
            `ifin_remote_loc_lon` Nullable(Decimal(9, 6)),
            `ifin_remote_manufac` LowCardinality(Nullable(String)),
            `ifin_remote_model` LowCardinality(Nullable(String)),
            `ifin_remote_network` LowCardinality(Nullable(String)),
            `ifin_remote_os` LowCardinality(Nullable(String)),
            `ifin_remote_port` LowCardinality(Nullable(String)),
            `ifin_remote_role` LowCardinality(Nullable(String)),
            `ifin_remote_short_name` LowCardinality(Nullable(String)),
            `ifin_remote_state` LowCardinality(Nullable(String)),
            `ifin_site` LowCardinality(Nullable(String)),
            `ifin_speed` Nullable(UInt32),
            `ifin_visibility` LowCardinality(Nullable(String)),
            `ifin_vrtr_ifglobalindex` Nullable(UInt32),
            `ifin_vrtr_ifindex` Nullable(String),
            `ifin_vrtr_name` LowCardinality(Nullable(String)),
            `ifout_description` Nullable(String),
            `ifout_device` LowCardinality(Nullable(String)),
            `ifout_id` Nullable(String),
            `ifout_ifindex` Nullable(UInt32),
            `ifout_edge` Bool,
            `ifout_ipv4` Nullable(IPv4),
            `ifout_ipv6` Nullable(IPv6),
            `ifout_name` Nullable(String),
            `ifout_netflow_index` Nullable(UInt32),
            `ifout_peer_asn`  Nullable(UInt32),
            `ifout_peer_ipv4` Nullable(IPv4),
            `ifout_peer_ipv6` Nullable(IPv6),
            `ifout_port_name` Nullable(String),
            `ifout_remote_device` LowCardinality(Nullable(String)),
            `ifout_remote_full_name` LowCardinality(Nullable(String)),
            `ifout_remote_id` Nullable(String),
            `ifout_remote_lldp_device` LowCardinality(Nullable(String)),
            `ifout_remote_lldp_port` LowCardinality(Nullable(String)),
            `ifout_remote_loc_name` LowCardinality(Nullable(String)),
            `ifout_remote_loc_type` LowCardinality(Nullable(String)),
            `ifout_remote_loc_lat` Nullable(Decimal(8, 6)),
            `ifout_remote_loc_lon` Nullable(Decimal(9, 6)),
            `ifout_remote_manufac` LowCardinality(Nullable(String)),
            `ifout_remote_model` LowCardinality(Nullable(String)),
            `ifout_remote_network` LowCardinality(Nullable(String)),
            `ifout_remote_os` LowCardinality(Nullable(String)),
            `ifout_remote_port` LowCardinality(Nullable(String)),
            `ifout_remote_role` LowCardinality(Nullable(String)),
            `ifout_remote_short_name` LowCardinality(Nullable(String)),
            `ifout_remote_state` LowCardinality(Nullable(String)),
            `ifout_site` LowCardinality(Nullable(String)),
            `ifout_speed` Nullable(UInt32),
            `ifout_visibility` LowCardinality(Nullable(String)),
            `ifout_vrtr_ifglobalindex` Nullable(UInt32),
            `ifout_vrtr_ifindex` Nullable(String),
            `ifout_vrtr_name` LowCardinality(Nullable(String)),
            `ip_tos` Nullable(UInt8),
            `ip_version`  Nullable(UInt8),
            `ipv6_flow_label` Nullable(UInt32),
            `mpls_bottom_label` Nullable(UInt32),
            `mpls_exp` Array(Nullable(UInt8)),
            `mpls_labels` Array(Nullable(UInt32)),
            `mpls_pw_id` Nullable(UInt32),
            `mpls_stack_depth` Nullable(UInt32),
            `mpls_top_label` Nullable(UInt32),
            `mpls_top_label_ip` Nullable(IPv6),
            `mpls_top_label_type` Nullable(UInt32),
            `mpls_vpn_rd` LowCardinality(Nullable(String)),
            `protocol` LowCardinality(Nullable(String)),
            `scireg_dst_discipline` LowCardinality(Nullable(String)),
            `scireg_dst_loc_lat` Nullable(Decimal(8, 6)),
            `scireg_dst_loc_lon` Nullable(Decimal(9, 6)),
            `scireg_dst_org_abbr` LowCardinality(Nullable(String)),
            `scireg_dst_org_name` LowCardinality(Nullable(String)),
            `scireg_dst_project_names` Array(LowCardinality(Nullable(String))),
            `scireg_dst_resource` LowCardinality(Nullable(String)),
            `scireg_dst_resource_abbr` LowCardinality(Nullable(String)),
            `scireg_dst_role` LowCardinality(Nullable(String)),
            `scireg_src_discipline` LowCardinality(Nullable(String)),
            `scireg_src_loc_lat` Nullable(Decimal(8, 6)),
            `scireg_src_loc_lon` Nullable(Decimal(9, 6)),
            `scireg_src_org_abbr` LowCardinality(Nullable(String)),
            `scireg_src_org_name` LowCardinality(Nullable(String)),
            `scireg_src_project_names` Array(LowCardinality(Nullable(String))),
            `scireg_src_resource` LowCardinality(Nullable(String)),
            `scireg_src_resource_abbr` LowCardinality(Nullable(String)),
            `scireg_src_role` LowCardinality(Nullable(String)),
            `src_as_name` LowCardinality(Nullable(String)),
            `src_asn` UInt32,
            `src_continent` LowCardinality(Nullable(String)),
            `src_country_name` LowCardinality(Nullable(String)),
            `src_ip` IPv6,
            `src_loc_lat` Nullable(Decimal(8, 6)),
            `src_loc_lon` Nullable(Decimal(9, 6)),
            `src_org` LowCardinality(Nullable(String)),
            `src_port` UInt16,
            `src_pref_loc_lat` Nullable(Decimal(8, 6)),
            `src_pref_loc_lon` Nullable(Decimal(9, 6)),
            `src_pref_org` LowCardinality(Nullable(String)),
            `src_pub_asn` Nullable(UInt32),
            `src_region_iso_code` LowCardinality(Nullable(String)),
            `src_region_name` LowCardinality(Nullable(String)),
            `traffic_class` LowCardinality(Nullable(String)),
            `vrf_egress_id` Nullable(UInt32),
            `vrf_ingress_id` Nullable(UInt32),
            `bits_per_sec` Nullable(Float64),
            `duration` Nullable(Float64),
            `max_pkt_len` Nullable(Float64),
            `max_ttl` Nullable(Float64),
            `min_pkt_len` Nullable(Float64),
            `min_ttl` Nullable(Float64),
            `num_bits` Nullable(Float64),
            `num_pkts` Nullable(Float64),
            `pkts_per_sec` Nullable(Float64)
        )
        ENGINE = MergeTree
        PARTITION BY toYYYYMMDD(`start_ts`)
        ORDER BY (`src_asn`,`dst_asn`, `src_ip`,`dst_ip`, `start_ts`)
        TTL start_ts + INTERVAL 7 DAY
        SETTINGS index_granularity = 8192
        """

        self.column_names = [
            "start_ts",
            "end_ts",
            "policy_originator",
            "policy_level",
            "policy_scopes",
            "app_name",
            "app_port",
            "bgp_as_path",
            "bgp_as_path_name",
            "bgp_as_path_org",
            "bgp_as_path_padding",
            "bgp_as_path_padded_len",
            "bgp_comms",
            "bgp_ecomms",
            "bgp_lcomms",
            "bgp_local_pref",
            "bgp_med",
            "bgp_next_hop",
            "bgp_peer_as_dst",
            "bgp_peer_as_dst_name",
            "bgp_peer_as_dst_org",
            "collector_id",
            "country_scope",
            "device_ip",
            "device_name",
            "device_loc_name",
            "device_loc_type",
            "device_loc_lat",
            "device_loc_lon",
            "device_manufac",
            "device_model",
            "device_network",
            "device_os",
            "device_role",
            "device_state",
            "dscp",
            "dst_as_name",
            "dst_asn",
            "dst_continent",
            "dst_country_name",
            "dst_ip",
            "dst_loc_lat",
            "dst_loc_lon",
            "dst_org",
            "dst_port",
            "dst_pref_loc_lat",
            "dst_pref_loc_lon",
            "dst_pref_org",
            "dst_pub_asn",
            "dst_region_iso_code",
            "dst_region_name",
            "esdb_dst_org_full_name",
            "esdb_dst_org_funding_agency",
            "esdb_dst_org_hide",
            "esdb_dst_org_short_name",
            "esdb_dst_org_types",
            "esdb_dst_svc_labels",
            "esdb_dst_svc_prefix_group_names",
            "esdb_dst_svc_types",
            "esdb_src_org_full_name",
            "esdb_src_org_funding_agency",
            "esdb_src_org_hide",
            "esdb_src_org_short_name",
            "esdb_src_org_types",
            "esdb_src_svc_labels",
            "esdb_src_svc_prefix_group_names",
            "esdb_src_svc_types",
            "flow_type",
            "ifin_description",
            "ifin_device",
            "ifin_id",
            "ifin_ifindex",
            "ifin_edge",
            "ifin_ipv4",
            "ifin_ipv6",
            "ifin_name",
            "ifin_netflow_index",
            "ifin_peer_as_name",
            "ifin_peer_asn",
            "ifin_peer_ip",
            "ifin_port_name",
            "ifin_remote_device",
            "ifin_remote_full_name",
            "ifin_remote_id",
            "ifin_remote_lldp_device",
            "ifin_remote_lldp_port",
            "ifin_remote_loc_name",
            "ifin_remote_loc_type",
            "ifin_remote_loc_lat",
            "ifin_remote_loc_lon",
            "ifin_remote_manufac",
            "ifin_remote_model",
            "ifin_remote_network",
            "ifin_remote_os",
            "ifin_remote_port",
            "ifin_remote_role",
            "ifin_remote_short_name",
            "ifin_remote_state",
            "ifin_site",
            "ifin_speed",
            "ifin_visibility",
            "ifin_vrtr_ifglobalindex",
            "ifin_vrtr_ifindex",
            "ifin_vrtr_name",
            "ifout_description",
            "ifout_device",
            "ifout_id",
            "ifout_ifindex",
            "ifout_edge",
            "ifout_ipv4",
            "ifout_ipv6",
            "ifout_name",
            "ifout_netflow_index",
            "ifout_peer_asn",
            "ifout_peer_ipv4",
            "ifout_peer_ipv6",
            "ifout_port_name",
            "ifout_remote_device",
            "ifout_remote_full_name",
            "ifout_remote_id",
            "ifout_remote_lldp_device",
            "ifout_remote_lldp_port",
            "ifout_remote_loc_name",
            "ifout_remote_loc_type",
            "ifout_remote_loc_lat",
            "ifout_remote_loc_lon",
            "ifout_remote_manufac",
            "ifout_remote_model",
            "ifout_remote_network",
            "ifout_remote_os",
            "ifout_remote_port",
            "ifout_remote_role",
            "ifout_remote_short_name",
            "ifout_remote_state",
            "ifout_site",
            "ifout_speed",
            "ifout_visibility",
            "ifout_vrtr_ifglobalindex",
            "ifout_vrtr_ifindex",
            "ifout_vrtr_name",
            "ip_tos",
            "ip_version",
            "ipv6_flow_label",
            "mpls_bottom_label",
            "mpls_exp",
            "mpls_labels",
            "mpls_pw_id",
            "mpls_stack_depth",
            "mpls_top_label",
            "mpls_top_label_ip",
            "mpls_top_label_type",
            "mpls_vpn_rd",
            "protocol",
            "scireg_dst_discipline",
            "scireg_dst_loc_lat",
            "scireg_dst_loc_lon",
            "scireg_dst_org_abbr",
            "scireg_dst_org_name",
            "scireg_dst_project_names",
            "scireg_dst_resource",
            "scireg_dst_resource_abbr",
            "scireg_dst_role",
            "scireg_src_discipline",
            "scireg_src_loc_lat",
            "scireg_src_loc_lon",
            "scireg_src_org_abbr",
            "scireg_src_org_name",
            "scireg_src_project_names",
            "scireg_src_resource",
            "scireg_src_resource_abbr",
            "scireg_src_role",
            "src_as_name",
            "src_asn",
            "src_continent",
            "src_country_name",
            "src_ip",
            "src_loc_lat",
            "src_loc_lon",
            "src_org",
            "src_port",
            "src_pref_loc_lat",
            "src_pref_loc_lon",
            "src_pref_org",
            "src_pub_asn",
            "src_region_iso_code",
            "src_region_name",
            "traffic_class",
            "vrf_egress_id",
            "vrf_ingress_id",
            "bits_per_sec",
            "duration",
            "max_pkt_len",
            "max_ttl",
            "min_pkt_len",
            "min_ttl",
            "num_bits",
            "num_pkts",
            "pkts_per_sec",
        ]

    def _build_message(self, value: dict, msg_metadata: dict) -> dict:
        #check required fields
        required_fields = [
            ['start'], 
            ['end'], 
            ['meta', 'dst_asn'], 
            ['meta', 'dst_ip'], 
            ['meta', 'dst_port'], 
            ['meta', 'src_asn'], 
            ['meta', 'src_ip'], 
            ['meta', 'src_port']
        ]
        for fields in required_fields:
            v = None
            for field in fields:
                if v is None:
                    v = value.get(field, None)
                else:
                    v = v.get(field, None)
                if v is None:
                    self.logger.error(f"Missing required field '{field}' in message value")
                    return None

        #build padding array
        bgp_padding = []
        for i in range(0, 20):
            padding = value.get("meta", {}).get("bgp", {}).get("as_hop{}_padding".format(i), None)
            if padding is None:
                break
            try:
                padding = int(padding)
            except ValueError:
                self.logger.error(f"Invalid bgp padding value: {padding}")
                break
            bgp_padding.append(padding)

        # build mpls_exp array
        mpls_exp = []
        for i in range(0, 20):
            exp = value.get("meta", {}).get("mpls", {}).get("exp{}".format(i), None)
            if exp is None:
                break
            try:
                exp = int(exp)
            except ValueError:
                self.logger.error(f"Invalid mpls exp value: {exp}")
                break
            mpls_exp.append(exp)

        return {
            "start_ts": value.get("start"),
            "end_ts": value.get("end"),
            "policy_originator": value.get("policy", {}).get("originator", None),
            "policy_level": value.get("policy", {}).get("level", None),
            "policy_scopes": value.get("policy", {}).get("scopes", []),
            "app_name": value.get("meta", {}).get("app_name", None),
            "app_port": value.get("meta", {}).get("app_port", 0),
            "bgp_as_path": value.get("meta", {}).get("bgp", {}).get("as_path", []),
            "bgp_as_path_name": value.get("meta", {}).get("bgp", {}).get("as_path_name", []),
            "bgp_as_path_org": value.get("meta", {}).get("bgp", {}).get("as_path_org", []),
            "bgp_as_path_padding": bgp_padding,
            "bgp_as_path_padded_len": value.get("meta", {}).get("bgp", {}).get("as_path_padded_len", None),
            "bgp_comms": value.get("meta", {}).get("bgp", {}).get("comms", []),
            "bgp_ecomms": value.get("meta", {}).get("bgp", {}).get("ecomms", []),
            "bgp_lcomms": value.get("meta", {}).get("bgp", {}).get("lcomms", []),
            "bgp_local_pref": value.get("meta", {}).get("bgp", {}).get("local_pref", None),
            "bgp_med": value.get("meta", {}).get("bgp", {}).get("med", None),
            "bgp_next_hop": value.get("meta", {}).get("bgp", {}).get("next_hop", None),
            "bgp_peer_as_dst": value.get("meta", {}).get("bgp", {}).get("peer_as_dst", None),
            "bgp_peer_as_dst_name": value.get("meta", {}).get("bgp", {}).get("peer_as_dst_name", None),
            "bgp_peer_as_dst_org": value.get("meta", {}).get("bgp", {}).get("peer_as_dst_org", None),
            "collector_id": value.get("meta", {}).get("sensor_id", None),
            "country_scope": value.get("meta", {}).get("country_scope", None),
            "device_ip":  value.get("meta", {}).get("router", {}).get("ip", None),
            "device_name": value.get("meta", {}).get("router", {}).get("name", None),
            "device_loc_name": value.get("meta", {}).get("device_info", {}).get("loc_name", None),
            "device_loc_type": value.get("meta", {}).get("device_info", {}).get("loc_type", None),
            "device_loc_lat": value.get("meta", {}).get("device_info", {}).get("location", {}).get("lat", None),
            "device_loc_lon": value.get("meta", {}).get("device_info", {}).get("location", {}).get("lon", None),
            "device_manufac": value.get("meta", {}).get("device_info", {}).get("manufacturer", None),
            "device_model": value.get("meta", {}).get("device_info", {}).get("model", None),
            "device_network": value.get("meta", {}).get("device_info", {}).get("network", None),
            "device_os": value.get("meta", {}).get("device_info", {}).get("os", None),
            "device_role": value.get("meta", {}).get("device_info", {}).get("role", None),
            "device_state": value.get("meta", {}).get("device_info", {}).get("state", None),
            "dscp": value.get("meta", {}).get("dscp", None),
            "dst_as_name": value.get("meta", {}).get("dst_as_name", None),
            "dst_asn":  value.get("meta", {}).get("dst_asn", None),
            "dst_continent": value.get("meta", {}).get("dst_continent", None),
            "dst_country_name": value.get("meta", {}).get("dst_country_name", None),
            "dst_ip": value.get("meta", {}).get("dst_ip"),
            "dst_loc_lat": value.get("meta", {}).get("dst_location", {}).get("lat", None),
            "dst_loc_lon": value.get("meta", {}).get("dst_location", {}).get("lon", None),
            "dst_org": value.get("meta", {}).get("dst_organization", None),
            "dst_port": value.get("meta", {}).get("dst_port", None),
            "dst_pref_loc_lat": value.get("meta", {}).get("dst_preferred_location", {}).get("lat", None),
            "dst_pref_loc_lon": value.get("meta", {}).get("dst_preferred_location", {}).get("lon", None),
            "dst_pref_org": value.get("meta", {}).get("dst_preferred_org", None),
            "dst_pub_asn":  value.get("meta", {}).get("dst_pub_asn", None),
            "dst_region_iso_code": value.get("meta", {}).get("dst_region_iso_code", None),
            "dst_region_name": value.get("meta", {}).get("dst_region_name", None),
            "esdb_dst_org_full_name": value.get("meta", {}).get("esdb", {}).get("dst", {}).get("org", {}).get("full_name", None),
            "esdb_dst_org_funding_agency": value.get("meta", {}).get("esdb", {}).get("dst", {}).get("org", {}).get("funding_agency", None),
            "esdb_dst_org_hide": value.get("meta", {}).get("esdb", {}).get("dst", {}).get("org", {}).get("hide", False),
            "esdb_dst_org_short_name": value.get("meta", {}).get("esdb", {}).get("dst", {}).get("org", {}).get("short_name", None),
            "esdb_dst_org_types": value.get("meta", {}).get("esdb", {}).get("dst", {}).get("org", {}).get("types", []),
            "esdb_dst_svc_labels": value.get("meta", {}).get("esdb", {}).get("dst", {}).get("service", {}).get("label", []),
            "esdb_dst_svc_prefix_group_names": value.get("meta", {}).get("esdb", {}).get("dst", {}).get("service", {}).get("prefix_group_name", []),
            "esdb_dst_svc_types": value.get("meta", {}).get("esdb", {}).get("dst", {}).get("service", {}).get("type", []),
            "esdb_src_org_full_name": value.get("meta", {}).get("esdb", {}).get("src", {}).get("org", {}).get("full_name", None),
            "esdb_src_org_funding_agency": value.get("meta", {}).get("esdb", {}).get("src", {}).get("org", {}).get("funding_agency", None),
            "esdb_src_org_hide": value.get("meta", {}).get("esdb", {}).get("src", {}).get("org", {}).get("hide", False),
            "esdb_src_org_short_name": value.get("meta", {}).get("esdb", {}).get("src", {}).get("org", {}).get("short_name", None),
            "esdb_src_org_types": value.get("meta", {}).get("esdb", {}).get("src", {}).get("org", {}).get("types", []),
            "esdb_src_svc_labels": value.get("meta", {}).get("esdb", {}).get("src", {}).get("service", {}).get("label", []),
            "esdb_src_svc_prefix_group_names": value.get("meta", {}).get("esdb", {}).get("src", {}).get("service", {}).get("prefix_group_name", []),
            "esdb_src_svc_types": value.get("meta", {}).get("esdb", {}).get("src", {}).get("service", {}).get("type", []),
            "flow_type": value.get("meta", {}).get("flow_type", None),
            "ifin_description": value.get("meta", {}).get("iface_in", {}).get("description", None),
            "ifin_device": value.get("meta", {}).get("iface_in", {}).get("device", None),
            "ifin_id": value.get("meta", {}).get("iface_in", {}).get("id", None),
            "ifin_ifindex": value.get("meta", {}).get("iface_in", {}).get("ifindex", None),
            "ifin_edge": value.get("meta", {}).get("iface_in", {}).get("intercloud", False),
            "ifin_ipv4": value.get("meta", {}).get("iface_in", {}).get("ipv4", None),
            "ifin_ipv6": value.get("meta", {}).get("iface_in", {}).get("ipv6", None),
            "ifin_name": value.get("meta", {}).get("iface_in", {}).get("name", None),
            "ifin_netflow_index": value.get("meta", {}).get("iface_in", {}).get("netflow_index", None),
            "ifin_peer_as_name": value.get("meta", {}).get("iface_in", {}).get("peer", {}).get("as_name", None),
            "ifin_peer_asn": value.get("meta", {}).get("iface_in", {}).get("peer", {}).get("asn", None),
            "ifin_peer_ip": value.get("meta", {}).get("iface_in", {}).get("peer", {}).get("ip", None),
            "ifin_port_name": value.get("meta", {}).get("iface_in", {}).get("port_name", None),
            "ifin_remote_device": value.get("meta", {}).get("iface_in", {}).get("remote", {}).get("device", None),
            "ifin_remote_full_name": value.get("meta", {}).get("iface_in", {}).get("remote", {}).get("full_name", None),
            "ifin_remote_id": value.get("meta", {}).get("iface_in", {}).get("remote", {}).get("id", None),
            "ifin_remote_lldp_device": value.get("meta", {}).get("iface_in", {}).get("remote", {}).get("lldp_device", None),
            "ifin_remote_lldp_port": value.get("meta", {}).get("iface_in", {}).get("remote", {}).get("lldp_port", None),
            "ifin_remote_loc_name": value.get("meta", {}).get("iface_in", {}).get("remote", {}).get("loc_name", None),
            "ifin_remote_loc_type": value.get("meta", {}).get("iface_in", {}).get("remote", {}).get("loc_type", None),
            "ifin_remote_loc_lat": value.get("meta", {}).get("iface_in", {}).get("remote", {}).get("location", {}).get("lat", None),
            "ifin_remote_loc_lon": value.get("meta", {}).get("iface_in", {}).get("remote", {}).get("location", {}).get("lon", None),
            "ifin_remote_manufac": value.get("meta", {}).get("iface_in", {}).get("remote", {}).get("manufacturer", None),
            "ifin_remote_model": value.get("meta", {}).get("iface_in", {}).get("remote", {}).get("model", None),
            "ifin_remote_network": value.get("meta", {}).get("iface_in", {}).get("remote", {}).get("network", None),
            "ifin_remote_os": value.get("meta", {}).get("iface_in", {}).get("remote", {}).get("os", None),
            "ifin_remote_port": value.get("meta", {}).get("iface_in", {}).get("remote", {}).get("port", None),
            "ifin_remote_role": value.get("meta", {}).get("iface_in", {}).get("remote", {}).get("role", None),
            "ifin_remote_short_name": value.get("meta", {}).get("iface_in", {}).get("remote", {}).get("short_name", None),
            "ifin_remote_state": value.get("meta", {}).get("iface_in", {}).get("remote", {}).get("state", None),
            "ifin_site": value.get("meta", {}).get("iface_in", {}).get("site", None),
            "ifin_speed": value.get("meta", {}).get("iface_in", {}).get("speed", None),
            "ifin_visibility": value.get("meta", {}).get("iface_in", {}).get("visibility", None),
            "ifin_vrtr_ifglobalindex": value.get("meta", {}).get("iface_in", {}).get("vrtrifglobalindex", None),
            "ifin_vrtr_ifindex": value.get("meta", {}).get("iface_in", {}).get("vrtrifindex", None),
            "ifin_vrtr_name": value.get("meta", {}).get("iface_in", {}).get("vrtrname", "default"),
            "ifout_description": value.get("meta", {}).get("iface_out", {}).get("description", None),
            "ifout_device": value.get("meta", {}).get("iface_out", {}).get("device", None),
            "ifout_id": value.get("meta", {}).get("iface_out", {}).get("id", None),
            "ifout_ifindex": value.get("meta", {}).get("iface_out", {}).get("ifindex", None),
            "ifout_edge": value.get("meta", {}).get("iface_out", {}).get("intercloud", False),
            "ifout_ipv4": value.get("meta", {}).get("iface_out", {}).get("ipv4", None),
            "ifout_ipv6": value.get("meta", {}).get("iface_out", {}).get("ipv6", None),
            "ifout_name": value.get("meta", {}).get("iface_out", {}).get("name", None),
            "ifout_netflow_index": value.get("meta", {}).get("iface_out", {}).get("netflow_index", None),
            "ifout_peer_asn":  value.get("meta", {}).get("iface_out", {}).get("peer", {}).get("asn", None),
            "ifout_peer_ipv4": value.get("meta", {}).get("iface_out", {}).get("peer", {}).get("ipv4", None),
            "ifout_peer_ipv6": value.get("meta", {}).get("iface_out", {}).get("peer", {}).get("ipv6", None),
            "ifout_port_name": value.get("meta", {}).get("iface_out", {}).get("port_name", None),
            "ifout_remote_device": value.get("meta", {}).get("iface_out", {}).get("remote", {}).get("device", None),
            "ifout_remote_full_name": value.get("meta", {}).get("iface_out", {}).get("remote", {}).get("full_name", None),
            "ifout_remote_id": value.get("meta", {}).get("iface_out", {}).get("remote", {}).get("id", None),
            "ifout_remote_lldp_device": value.get("meta", {}).get("iface_out", {}).get("remote", {}).get("lldp_device", None),
            "ifout_remote_lldp_port": value.get("meta", {}).get("iface_out", {}).get("remote", {}).get("lldp_port", None),
            "ifout_remote_loc_name": value.get("meta", {}).get("iface_out", {}).get("remote", {}).get("loc_name", None),
            "ifout_remote_loc_type": value.get("meta", {}).get("iface_out", {}).get("remote", {}).get("loc_type", None),
            "ifout_remote_loc_lat": value.get("meta", {}).get("iface_out", {}).get("remote", {}).get("location", {}).get("lat", None),
            "ifout_remote_loc_lon": value.get("meta", {}).get("iface_out", {}).get("remote", {}).get("location", {}).get("lon", None),
            "ifout_remote_manufac": value.get("meta", {}).get("iface_out", {}).get("remote", {}).get("manufacturer", None),
            "ifout_remote_model": value.get("meta", {}).get("iface_out", {}).get("remote", {}).get("model", None),
            "ifout_remote_network": value.get("meta", {}).get("iface_out", {}).get("remote", {}).get("network", None),
            "ifout_remote_os": value.get("meta", {}).get("iface_out", {}).get("remote", {}).get("os", None),
            "ifout_remote_port": value.get("meta", {}).get("iface_out", {}).get("remote", {}).get("port", None),
            "ifout_remote_role": value.get("meta", {}).get("iface_out", {}).get("remote", {}).get("role", None),
            "ifout_remote_short_name": value.get("meta", {}).get("iface_out", {}).get("remote", {}).get("short_name", None),
            "ifout_remote_state": value.get("meta", {}).get("iface_out", {}).get("remote", {}).get("state", None),
            "ifout_site": value.get("meta", {}).get("iface_out", {}).get("site", None),
            "ifout_speed": value.get("meta", {}).get("iface_out", {}).get("speed", None),
            "ifout_visibility": value.get("meta", {}).get("iface_out", {}).get("visibility", None),
            "ifout_vrtr_ifglobalindex": value.get("meta", {}).get("iface_out", {}).get("vrtrifglobalindex", None),
            "ifout_vrtr_ifindex": value.get("meta", {}).get("iface_out", {}).get("vrtrifindex", None),
            "ifout_vrtr_name": value.get("meta", {}).get("iface_out", {}).get("vrtrname", "default"),
            "ip_tos": value.get("meta", {}).get("ip_tos", None),
            "ip_version":  value.get("meta", {}).get("ip_version", None),
            "ipv6_flow_label": value.get("meta", {}).get("ipv6", {}).get("flow_label", None),
            "mpls_bottom_label": value.get("meta", {}).get("mpls", {}).get("bottom_label", None),
            "mpls_exp": mpls_exp,
            "mpls_labels": value.get("meta", {}).get("mpls", {}).get("labels", []),
            "mpls_pw_id": value.get("meta", {}).get("mpls", {}).get("pw_id", None),
            "mpls_stack_depth": value.get("meta", {}).get("mpls", {}).get("stack_depth", None),
            "mpls_top_label": value.get("meta", {}).get("mpls", {}).get("top_label", None),
            "mpls_top_label_ip": value.get("meta", {}).get("mpls", {}).get("top_label_ip", None),
            "mpls_top_label_type": value.get("meta", {}).get("mpls", {}).get("top_label_type", None),
            "mpls_vpn_rd": value.get("meta", {}).get("mpls", {}).get("vpn_rd", None),
            "protocol": value.get("meta", {}).get("protocol", None),
            "scireg_dst_discipline": value.get("meta", {}).get("scireg", {}).get("dst", {}).get("discipline", None),
            "scireg_dst_loc_lat": value.get("meta", {}).get("scireg", {}).get("dst", {}).get("latitude", None),
            "scireg_dst_loc_lon": value.get("meta", {}).get("scireg", {}).get("dst", {}).get("longitude", None),
            "scireg_dst_org_abbr": value.get("meta", {}).get("scireg", {}).get("dst", {}).get("org_abbr", None),
            "scireg_dst_org_name": value.get("meta", {}).get("scireg", {}).get("dst", {}).get("org_name", None),
            "scireg_dst_project_names": value.get("meta", {}).get("scireg", {}).get("dst", {}).get("project_names", []),
            "scireg_dst_resource": value.get("meta", {}).get("scireg", {}).get("dst", {}).get("resource", None),
            "scireg_dst_resource_abbr": value.get("meta", {}).get("scireg", {}).get("dst", {}).get("resource_abbr", None),
            "scireg_dst_role": value.get("meta", {}).get("scireg", {}).get("dst", {}).get("role", None),
            "scireg_src_discipline": value.get("meta", {}).get("scireg", {}).get("src", {}).get("discipline", None),
            "scireg_src_loc_lat": value.get("meta", {}).get("scireg", {}).get("src", {}).get("latitude", None),
            "scireg_src_loc_lon": value.get("meta", {}).get("scireg", {}).get("src", {}).get("longitude", None),
            "scireg_src_org_abbr": value.get("meta", {}).get("scireg", {}).get("src", {}).get("org_abbr", None),
            "scireg_src_org_name": value.get("meta", {}).get("scireg", {}).get("src", {}).get("org_name", None),
            "scireg_src_project_names": value.get("meta", {}).get("scireg", {}).get("src", {}).get("project_names", []),
            "scireg_src_resource": value.get("meta", {}).get("scireg", {}).get("src", {}).get("resource", None),
            "scireg_src_resource_abbr": value.get("meta", {}).get("scireg", {}).get("src", {}).get("resource_abbr", None),
            "scireg_src_role": value.get("meta", {}).get("scireg", {}).get("src", {}).get("role", None),
            "src_as_name": value.get("meta", {}).get("src_as_name", "unknown"),
            "src_asn": value.get("meta", {}).get("src_asn", None),
            "src_continent": value.get("meta", {}).get("src_continent", None),
            "src_country_name": value.get("meta", {}).get("src_country_name", None),
            "src_ip": value.get("meta", {}).get("src_ip", None),
            "src_loc_lat": value.get("meta", {}).get("src_location", {}).get("latitude", None),
            "src_loc_lon": value.get("meta", {}).get("src_location", {}).get("longitude", None),
            "src_org": value.get("meta", {}).get("src_organization", None),
            "src_port": value.get("meta", {}).get("src_port", None),
            "src_pref_loc_lat": value.get("meta", {}).get("src_preferred_location", {}).get("lat", None),
            "src_pref_loc_lon": value.get("meta", {}).get("src_preferred_location", {}).get("lon", None),
            "src_pref_org": value.get("meta", {}).get("src_preferred_org", None),
            "src_pub_asn": value.get("meta", {}).get("src_pub_asn", None),
            "src_region_iso_code": value.get("meta", {}).get("src_region_iso_code", None),
            "src_region_name": value.get("meta", {}).get("src_region_name", None),
            "traffic_class": value.get("meta", {}).get("traffic_class", None),
            "vrf_egress_id": value.get("meta", {}).get("vrf", {}).get("egress_id", None),
            "vrf_ingress_id": value.get("meta", {}).get("vrf", {}).get("ingress_id", None),
            "bits_per_sec": value.get("values", {}).get("bits_per_second", None),
            "duration": value.get("values", {}).get("duration", None),
            "max_pkt_len": value.get("values", {}).get("max_packet_len", None),
            "max_ttl": value.get("values", {}).get("max_ttl", None),
            "min_pkt_len": value.get("values", {}).get("min_packet_len", None),
            "min_ttl": value.get("values", {}).get("min_ttl", None),
            "num_bits": value.get("values", {}).get("num_bits", None),
            "num_pkts": value.get("values", {}).get("num_packets", None),
            "pkts_per_sec": value.get("values", {}).get("packets_per_second", None)
        }
    
    def _message_to_columns(self, message: dict) -> list:
        cols = []
        for col in self.column_names:
            if col not in message.keys():
                raise ValueError(f"Missing column '{col}' in message")
            self.logger.debug(f"Column '{col}': {message.get(col)}")
            cols.append(message.get(col))
        return cols
